### ISSUE TITLE
Strongly app

### ISSUE THREAD

**Issue by kodburn** [bintrail/bintrail-swift-sdk#1]
Hi David,
The issue is unrelated to the current repo and it's about your "strongly" app. I thought it was the fastest way to contact you.

I believe it's the most beautiful app to track a workout routine and after hours of search there's nothing similar to this in the app store 😄  .

Unfortunately, I cannot buy the Pro version, the button doesn't work.

Is there a chance to fix it somehow?
Sorry for the inconvenience and thanks a lot, Ihor

**Comment by davidask** [comment]
Not sure how you found your way here, but please drop me an e-mail at david@formbound.com ☺️
